version: '3.9'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8011:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

